version: "3.9"
services:
  container-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27018:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
